# Generated by Django 2.0.2 on 2018-05-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('College_name', models.CharField(max_length=200)),
                ('Location', models.CharField(max_length=200)),
                ('Comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the Course Name', max_length=200)),
                ('summary', models.TextField(help_text='Enter brief description', max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='college',
            name='Courses_offered',
            field=models.ManyToManyField(help_text='Select Courses', to='Blog.Course'),
        ),
    ]
