# Generated by Django 2.0.2 on 2018-05-22 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='college',
            options={'ordering': ['College_name']},
        ),
    ]
