# Generated by Django 2.0.2 on 2018-05-21 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(help_text='Enter the Course Name', max_length=200),
        ),
    ]
