# Generated by Django 2.0.2 on 2018-05-22 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_auto_20180522_0514'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='Comment',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
