# Generated by Django 2.0.2 on 2018-05-23 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Commenting',
        ),
    ]
