# Generated by Django 2.0.2 on 2018-05-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_auto_20180523_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commenting',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
