# Generated by Django 2.0.2 on 2018-05-24 21:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_auto_20180524_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commenting',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 25, 2, 45, 33, 585334)),
        ),
    ]
